version: '2.1'
services:
  pcbuilder_db:
    restart: always
    image: postgres:14
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=pcdb_test
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432
  pcbuilder_server:
    restart: always
    ports:
      - 127.0.0.1:5000:5000
    image: pcbuilder_server
    depends_on:
      - pcbuilder_db
  pcbuilder_client:
    restart: always
    ports:
      - 127.0.0.1:8081:8080
    image: pcbuilder_client
    depends_on:
      - pcbuilder_server